"""Application configuration settings."""

from functools import lru_cache
from urllib.parse import quote_plus

try:  # pragma: no cover - compatibility shim for pydantic v1/v2
    from pydantic_settings import BaseSettings, SettingsConfigDict  # type: ignore
except ModuleNotFoundError:  # pragma: no cover - fallback for pydantic v1
    from pydantic import BaseSettings  # type: ignore
    SettingsConfigDict = None  # type: ignore[misc]

from pydantic import Field


class Settings(BaseSettings):
    """Application configuration values loaded from environment variables."""

    database_url: str | None = Field(
        default=None,
        description=(
            "Deprecated single-string database URL. Provided for backwards compatibility "
            "while migrating to the fine-grained Azure SQL settings."
        ),
    )
    db_driver: str = Field(
        ...,
        description="ODBC driver name to use when connecting to Azure SQL or SQL Server",
    )
    db_server: str = Field(
        ...,
        description="Fully qualified SQL Server host name (for Azure SQL include .database.windows.net)",
    )
    db_port: int = Field(
        default=1433,
        description="SQL Server port number",
    )
    db_name: str = Field(
        ...,
        description="Database name to connect to",
    )
    db_user: str = Field(
        ...,
        description="Database login or user name",
    )
    db_password: str = Field(
        ...,
        description="Password for the configured database user",
    )
    secret_key: str = Field(
        ...,
        description="Secret key for signing JWT tokens"
    )
    access_token_expire_minutes: int = Field(
        ...,
        description="Number of minutes before access tokens expire"
    )
    sendgrid_api_key: str | None = Field(
        default=None,
        description="SendGrid API key used for sending transactional emails via the REST API",
    )
    sendgrid_sender: str | None = Field(
        default=None,
        description="Email address that will appear as the sender of transactional messages",
    )
    openai_api_key: str | None = Field(
        default=None,
        description="OpenAI API key used to authenticate requests to the language model service",
    )
    openai_model: str = Field(
        default="gpt-4.1-mini",
        description="Default OpenAI model identifier used for structured assistant responses",
    )
    openai_base_url: str | None = Field(
        default=None,
        description="Optional custom base URL for the OpenAI compatible API",
    )
    openai_temperature: float = Field(
        ...,
        description="Sampling temperature for OpenAI structured responses",
        ge=0.0,
        le=2.0,
    )
    openai_max_output_tokens: int | None = Field(
        default=None,
        description="Optional limit for the number of tokens generated by the assistant",
    )
    azure_storage_connection_string: str = Field(
        ...,
        description="Azure Blob Storage connection string used to persist template and report files",
    )
    azure_storage_container_name: str = Field(
        ...,
        description="Azure Blob Storage container name where files will be stored",
    )
    app_timezone: str = Field(
        ...,
        description=(
            "IANA timezone identifier (or UTC offset such as 'UTC-05') used for"
            " timestamps like created_at, updated_at and deleted_at."
        ),
    )

    @property
    def odbc_connection_string(self) -> str:
        """Return the Azure SQL/SQL Server ODBC connection string."""

        return (
            f"Driver={{{self.db_driver}}};"
            f"Server=tcp:{self.db_server},{self.db_port};"
            f"Database={self.db_name};"
            f"Uid={self.db_user};"
            f"Pwd={self.db_password};"
            "Encrypt=yes;"
            "TrustServerCertificate=no;"
            "Connection Timeout=30;"
        )

    @property
    def sqlalchemy_database_url(self) -> str:
        """Return the SQLAlchemy URL for the configured SQL Server instance."""

        return f"mssql+pyodbc:///?odbc_connect={quote_plus(self.odbc_connection_string)}"

    if "SettingsConfigDict" in globals() and SettingsConfigDict is not None:
        model_config = SettingsConfigDict(
            env_file=".env",
            env_file_encoding="utf-8",
        )
    else:  # pragma: no cover - compatibility path for pydantic v1
        class Config:
            env_file = ".env"
            env_file_encoding = "utf-8"


@lru_cache
def get_settings() -> Settings:
    """Return cached application settings instance."""

    return Settings()
